### ISSUE TITLE
Test suite hangs if fish from PerlPowerTools is installed

### ISSUE THREAD

**Issue by eserte** [plicease/Shell-Config-Generate#10]
If https://metacpan.org/pod/distribution/PerlPowerTools/bin/fish is installed in the current PATH, then the Shell-Config-Generate-0.18 test suite hangs. Problem is that this fish does not fail on double dash options:
```
$ /usr/perl5.18.2/bin/fish --version
/usr/perl5.18.2/bin/fish version [unknown] calling Getopt::Std::getopts (version 1.07 [paranoid]),
running under Perl version 5.18.2.
  [Now continuing due to backward compatibility and excessive paranoia.
   See 'perldoc Getopt::Std' about $Getopt::Std::STANDARD_HELP_VERSION.]
Do you want to see instructions (y/n)?
```
Unknown single dash options are handled as expected, the command fails.
```
$ /usr/perl5.18.2/bin/fish -c 'exit 22'
Unknown option: c
Usage: /usr/perl5.18.2/bin/fish [-p]
```

**Comment by plicease** [comment]
I think this can be worked around pretty easy too. Should also set a timeout while I am at it, though that won't work on MSWin32.  We can probably assume that fish and jsh are not installed there.

**Comment by plicease** [comment]
I think installing ppt will probably break a bunch of stuff on Unix. It replaces a number of usually system tools with versions that are different in subtle ways.

**Comment by plicease** [comment]
This should now work with version 0.19.  I tested it with both the actual fish shell and with "fish" from ppt.  If you are still seeing this behavior then please reopen to let me know.

btw- I noticed that cpanm also hangs when you try and use it with ppt installed.  I am pretty sure that it isn't using fish, but I did not investigate further.
