### ISSUE TITLE
Spaces in commands somewhere

### ISSUE THREAD

**Issue by plicease** [plicease/Shell-Config-Generate#12]
I think this is the cause for this failure:

http://www.cpantesters.org/cpan/report/0ac47776-6c9c-1014-8ac0-6d61aff55ff3

On windows this can be handled by converting the name with spaces into a short version without spaces.

**Comment by plicease** [comment]
Adding a gist to this log in case the cpantesters one goes away.

https://gist.github.com/plicease/318b37a556370fcb61011ced15a5ccb9

**Comment by brad-mac** [comment]
This test failure looks more like another weird error on that particular test machine. Notice the PERL5LIB setting from the test report:

PERL5LIB=D:\STRAW(~1\data\.cpanm\work\1429598137.8732\Shell-Config-Generate-0.21\blib\lib;D:\STRAW(~1\data\.cpanm\work\1429598137.8732\Shell-Config-Generate-0.21\blib\arch;inc

Those opening parentheses (e.g. `D:\STRAW(~1\` are bogus; I'd recommend this issue simply be closed off.
