### ISSUE TITLE
Test fails if sysutils/clusterit is installed

### ISSUE THREAD

**Issue by eserte** [plicease/Shell-Config-Generate#8]
The FreeBSD package sysutils/clusterit includes a program "jsh" which is not a shell, but some kind of job scheduling program. Consequently the test suite fails if this package is installed:
```
jsh: Failed in jsh.c line 196: Connection refused 61
    # child exited with value 1
    # [src]
    # #!/usr/local/bin/jsh
    # alias myecho1="/usr/local/bin/perl5.8.9 /var/tmp/cpansmoker-1000/EwlZXot50t/fooecho.pl f00f";
    # myecho1 one two three
    # [out]

    #   Failed test 'arguments match'
    #   at t/alias.t line 43.
    #     Structures begin differing at:
    #          $got = undef
    #     $expected = ARRAY(0x41f06e90)
    # Looks like you failed 1 test of 1.

#   Failed test 'jsh'
#   at t/alias.t line 44.
# Looks like you failed 1 test of 17.
...
```
Probably there should be a check if jsh is really the expected program, maybe like the fish check in common.pl.

Note that FreeBSD has a shells/heirloom-sh package containing jsh, which is probably the right one.

**Comment by plicease** [comment]
Thanks for the report! Your analysis sounds exactly right. I will fix the test or just skip it. It is a pretty obscure shell anyway

**Comment by plicease** [comment]
I think this should be fixed in 0.18.  I don't have sysutils/clusterit installed on my freebsd box, so if you could verify that it passed the test suite I'd be grateful.

**Comment by eserte** [comment]
Yes, 0.18 passes now on my system.

**Comment by plicease** [comment]
Thanks.  I noticed your PR only after I made my own fix!
